from data_loader import download_and_save

TICKERS = [
    "RELIANCE.NS", "TCS.NS", "INFY.NS", "HDFCBANK.NS", "ICICIBANK.NS",
    "KOTAKBANK.NS", "SBIN.NS", "LT.NS", "ITC.NS", "HINDUNILVR.NS",
    "AXISBANK.NS", "ASIANPAINT.NS", "MARUTI.NS", "SUNPHARMA.NS", "ULTRACEMCO.NS",
    "TITAN.NS", "WIPRO.NS", "NESTLEIND.NS", "BAJFINANCE.NS", "BAJAJFINSV.NS",
    "ONGC.NS", "NTPC.NS", "POWERGRID.NS", "COALINDIA.NS", "TATASTEEL.NS",
    "JSWSTEEL.NS", "HCLTECH.NS", "TECHM.NS", "DRREDDY.NS", "CIPLA.NS",
    "DIVISLAB.NS", "ADANIENT.NS", "ADANIPORTS.NS", "BPCL.NS", "BRITANNIA.NS",
    "EICHERMOT.NS", "GRASIM.NS", "HEROMOTOCO.NS", "HDFCLIFE.NS", "SBILIFE.NS",
    "INDUSINDBK.NS", "BAJAJ-AUTO.NS", "APOLLOHOSP.NS", "TATAMOTORS.NS", "SHREECEM.NS",
    "UPL.NS", "PIDILITIND.NS", "DABUR.NS", "ICICIPRULI.NS", "M&M.NS"
]

START_DATE = "2014-01-01"
END_DATE = "2024-01-01"

download_and_save(TICKERS, START_DATE, END_DATE)